//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalprj.myDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDatabase : DbContext
    {
        public MyDatabase()
            : base("name=QuanLyCafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ban> Bans { get; set; }
        public virtual DbSet<ChiTietHoaDonBanHang> ChiTietHoaDonBanHangs { get; set; }
        public virtual DbSet<ChiTietHoaDonNhapHang> ChiTietHoaDonNhapHangs { get; set; }
        public virtual DbSet<HoaDonBanHang> HoaDonBanHangs { get; set; }
        public virtual DbSet<HoaDonNhapHang> HoaDonNhapHangs { get; set; }
        public virtual DbSet<KhoHang> KhoHangs { get; set; }
        public virtual DbSet<LoginNhanVien> LoginNhanViens { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<ThucDon> ThucDons { get; set; }
        public virtual DbSet<BaoCaoBanHang> BaoCaoBanHangs { get; set; }
        public virtual DbSet<BaoCaoNhapHang> BaoCaoNhapHangs { get; set; }
        public virtual DbSet<ChiTietBanHang> ChiTietBanHangs { get; set; }
        public virtual DbSet<ChiTietNhapHang> ChiTietNhapHangs { get; set; }
        public virtual DbSet<TimKiemNhanVien> TimKiemNhanViens { get; set; }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThu")]
        public virtual IQueryable<f_DoanhThu_Result> f_DoanhThu(Nullable<System.DateTime> daybegin, Nullable<System.DateTime> dayend)
        {
            var daybeginParameter = daybegin.HasValue ?
                new ObjectParameter("daybegin", daybegin) :
                new ObjectParameter("daybegin", typeof(System.DateTime));
    
            var dayendParameter = dayend.HasValue ?
                new ObjectParameter("dayend", dayend) :
                new ObjectParameter("dayend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThu_Result>("[QuanLyCafeEntities].[f_DoanhThu](@daybegin, @dayend)", daybeginParameter, dayendParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThuNgay_BanHang")]
        public virtual IQueryable<f_DoanhThuNgay_BanHang_Result> f_DoanhThuNgay_BanHang(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuNgay_BanHang_Result>("[QuanLyCafeEntities].[f_DoanhThuNgay_BanHang](@date)", dateParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThuNgay_NhapHang")]
        public virtual IQueryable<f_DoanhThuNgay_NhapHang_Result> f_DoanhThuNgay_NhapHang(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuNgay_NhapHang_Result>("[QuanLyCafeEntities].[f_DoanhThuNgay_NhapHang](@date)", dateParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayCTHoaDonBanHang")]
        public virtual IQueryable<f_LayCTHoaDonBanHang_Result> f_LayCTHoaDonBanHang(string iDhoaDonBH)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayCTHoaDonBanHang_Result>("[QuanLyCafeEntities].[f_LayCTHoaDonBanHang](@IDhoaDonBH)", iDhoaDonBHParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayCTHoaDonNhapHang")]
        public virtual IQueryable<f_LayCTHoaDonNhapHang_Result> f_LayCTHoaDonNhapHang(string iDhoaDonNH)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayCTHoaDonNhapHang_Result>("[QuanLyCafeEntities].[f_LayCTHoaDonNhapHang](@IDhoaDonNH)", iDhoaDonNHParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayThongTinLogin")]
        public virtual IQueryable<f_LayThongTinLogin_Result> f_LayThongTinLogin(string loginName)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("loginName", loginName) :
                new ObjectParameter("loginName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayThongTinLogin_Result>("[QuanLyCafeEntities].[f_LayThongTinLogin](@loginName)", loginNameParameter);
        }
    
        public virtual int sp_Delete_Ban(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_Ban", iDParameter);
        }
    
        public virtual int sp_Delete_ChiTietHoaDonBanHang(string iDhoaDonBH, string iDthucDon)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            var iDthucDonParameter = iDthucDon != null ?
                new ObjectParameter("IDthucDon", iDthucDon) :
                new ObjectParameter("IDthucDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ChiTietHoaDonBanHang", iDhoaDonBHParameter, iDthucDonParameter);
        }
    
        public virtual int sp_Delete_ChiTietHoaDonNhapHang(string iDhoaDonNH, string iDhang)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            var iDhangParameter = iDhang != null ?
                new ObjectParameter("IDhang", iDhang) :
                new ObjectParameter("IDhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ChiTietHoaDonNhapHang", iDhoaDonNHParameter, iDhangParameter);
        }
    
        public virtual int sp_Delete_HoaDonBanHang(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_HoaDonBanHang", iDParameter);
        }
    
        public virtual int sp_Delete_HoaDonNhapHang(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_HoaDonNhapHang", iDParameter);
        }
    
        public virtual int sp_Delete_KhoHang(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_KhoHang", iDParameter);
        }
    
        public virtual int sp_Delete_LoginNhanVien(string loginName)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_LoginNhanVien", loginNameParameter);
        }
    
        public virtual int sp_Delete_NhanVien(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_NhanVien", iDParameter);
        }
    
        public virtual int sp_Delete_ThucDon(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ThucDon", iDParameter);
        }
    
        public virtual int sp_Insert_Ban(string iD, string tenBan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("TenBan", tenBan) :
                new ObjectParameter("TenBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_Ban", iDParameter, tenBanParameter);
        }
    
        public virtual int sp_Insert_ChiTietHoaDonBanHang(string iDhoaDonBH, string iDthucDon, Nullable<int> soLuong)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            var iDthucDonParameter = iDthucDon != null ?
                new ObjectParameter("IDthucDon", iDthucDon) :
                new ObjectParameter("IDthucDon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ChiTietHoaDonBanHang", iDhoaDonBHParameter, iDthucDonParameter, soLuongParameter);
        }
    
        public virtual int sp_Insert_ChiTietHoaDonNhapHang(string iDhoaDonNH, string iDhang, Nullable<int> soLuong)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            var iDhangParameter = iDhang != null ?
                new ObjectParameter("IDhang", iDhang) :
                new ObjectParameter("IDhang", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ChiTietHoaDonNhapHang", iDhoaDonNHParameter, iDhangParameter, soLuongParameter);
        }
    
        public virtual int sp_Insert_HoaDonBanHang(string iD, string iDnhanVien, string iDban, Nullable<System.DateTime> ngaytao, Nullable<bool> daThanhToan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var iDbanParameter = iDban != null ?
                new ObjectParameter("IDban", iDban) :
                new ObjectParameter("IDban", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            var daThanhToanParameter = daThanhToan.HasValue ?
                new ObjectParameter("DaThanhToan", daThanhToan) :
                new ObjectParameter("DaThanhToan", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_HoaDonBanHang", iDParameter, iDnhanVienParameter, iDbanParameter, ngaytaoParameter, daThanhToanParameter);
        }
    
        public virtual int sp_Insert_HoaDonNhapHang(string iD, string iDnhanVien, Nullable<System.DateTime> ngayTao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_HoaDonNhapHang", iDParameter, iDnhanVienParameter, ngayTaoParameter);
        }
    
        public virtual int sp_Insert_KhoHang(string iD, string ten, string donViTinh, Nullable<int> soLuong, Nullable<float> donGia)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_KhoHang", iDParameter, tenParameter, donViTinhParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sp_Insert_LoginNhanVien(string iDNhanVien, string loginName, string password, Nullable<bool> permission, Nullable<System.DateTime> ngaytao)
        {
            var iDNhanVienParameter = iDNhanVien != null ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(string));
    
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var permissionParameter = permission.HasValue ?
                new ObjectParameter("Permission", permission) :
                new ObjectParameter("Permission", typeof(bool));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_LoginNhanVien", iDNhanVienParameter, loginNameParameter, passwordParameter, permissionParameter, ngaytaoParameter);
        }
    
        public virtual int sp_Insert_NhanVien(string iD, string hoTen, string sDT, string cMND, string diaChi, Nullable<System.DateTime> ngayVaoLam, Nullable<System.DateTime> ngayNghiViec)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_NhanVien", iDParameter, hoTenParameter, sDTParameter, cMNDParameter, diaChiParameter, ngayVaoLamParameter, ngayNghiViecParameter);
        }
    
        public virtual int sp_Insert_ThucDon(string iD, string ten, string donViTinh, Nullable<float> donGia)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ThucDon", iDParameter, tenParameter, donViTinhParameter, donGiaParameter);
        }
    
        public virtual int sp_Update_Ban(string iD, string tenBan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("TenBan", tenBan) :
                new ObjectParameter("TenBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_Ban", iDParameter, tenBanParameter);
        }
    
        public virtual int sp_Update_ChiTietHoaDonBanHang(string iDhoaDonBH, string iDthucDon, Nullable<int> soLuong)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            var iDthucDonParameter = iDthucDon != null ?
                new ObjectParameter("IDthucDon", iDthucDon) :
                new ObjectParameter("IDthucDon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ChiTietHoaDonBanHang", iDhoaDonBHParameter, iDthucDonParameter, soLuongParameter);
        }
    
        public virtual int sp_Update_ChiTietHoaDonNhapHang(string iDhoaDonNH, string iDhang, Nullable<int> soLuong)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            var iDhangParameter = iDhang != null ?
                new ObjectParameter("IDhang", iDhang) :
                new ObjectParameter("IDhang", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ChiTietHoaDonNhapHang", iDhoaDonNHParameter, iDhangParameter, soLuongParameter);
        }
    
        public virtual int sp_Update_HoaDonBanHang(string iD, string iDnhanVien, string iDban, Nullable<System.DateTime> ngaytao, Nullable<bool> daThanhToan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var iDbanParameter = iDban != null ?
                new ObjectParameter("IDban", iDban) :
                new ObjectParameter("IDban", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            var daThanhToanParameter = daThanhToan.HasValue ?
                new ObjectParameter("DaThanhToan", daThanhToan) :
                new ObjectParameter("DaThanhToan", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_HoaDonBanHang", iDParameter, iDnhanVienParameter, iDbanParameter, ngaytaoParameter, daThanhToanParameter);
        }
    
        public virtual int sp_Update_HoaDonNhapHang(string iD, string iDnhanVien, Nullable<System.DateTime> ngayTao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_HoaDonNhapHang", iDParameter, iDnhanVienParameter, ngayTaoParameter);
        }
    
        public virtual int sp_Update_KhoHang(string iD, string ten, string donViTinh, Nullable<int> soLuong, Nullable<float> donGia)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_KhoHang", iDParameter, tenParameter, donViTinhParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sp_Update_LoginNhanVien(string iDNhanVien, string loginName, string password, Nullable<bool> permission, Nullable<System.DateTime> ngaytao)
        {
            var iDNhanVienParameter = iDNhanVien != null ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(string));
    
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var permissionParameter = permission.HasValue ?
                new ObjectParameter("Permission", permission) :
                new ObjectParameter("Permission", typeof(bool));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_LoginNhanVien", iDNhanVienParameter, loginNameParameter, passwordParameter, permissionParameter, ngaytaoParameter);
        }
    
        public virtual int sp_Update_NhanVien(string iD, string hoTen, string sDT, string cMND, string diaChi, Nullable<System.DateTime> ngayVaoLam, Nullable<System.DateTime> ngayNghiViec)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_NhanVien", iDParameter, hoTenParameter, sDTParameter, cMNDParameter, diaChiParameter, ngayVaoLamParameter, ngayNghiViecParameter);
        }
    
        public virtual int sp_Update_ThucDon(string iD, string ten, string donViTinh, Nullable<float> donGia)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ThucDon", iDParameter, tenParameter, donViTinhParameter, donGiaParameter);
        }
    }
}
